export const userActions = {
  FETCH_USER: 'FETCH_USER',
  SIGNIN_REQUEST: 'SIGNIN_REQUEST',
  SIGNIN_SUCCESSFUL: 'SIGNIN_SUCCESSFUL',
  SIGNIN_ERROR: 'SIGNIN_ERROR',
  SIGNOUT_SUCCESSFUL: 'SIGNOUT_SUCCESSFUL',
  SIGNOUT_REQUEST: 'SIGNOUT_REQUEST',
  SIGNOUT_ERROR: 'SIGNOUT_ERROR',
};

export const gatheringActions = {
  FETCH_PLAYERS: 'FETCH_PLAYERS',
  JOIN_GATHERING: 'JOIN_GATHERING',
  LEAVE_GATHERING: 'LEAVE_GATHERING',
};

export const gameActions = {
  GAME_REQUESTED: 'GAME_REQUESTED',
  // GAME_CREATED: 'GAME_CREATED',
  GAME_STARTED: 'GAME_STARTED',
  GAME_ENDED: 'GAME_ENDED',
  MAKE_PLAY: 'MAKE_PLAY',
  PLAY_IN_PROGRESS: 'PLAY_IN_PROGRESS',
  PLAY_RECEIVED: 'PLAY_RECEIVED',
};
